/*
 * File: src/app/layout.tsx
 * Author: Harshita Gawas
 * Description: Layout for the Portfolio application.
 * Created on: 15/03/2026
 * Last Modified: 20/03/2026
 */
import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar/Navbar";
import "./globals.css";
import { SideIcons } from "@/components/SideIcons/SideIcons";
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "PortFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SideIcons />
        {children}
        <Footer />
      </body>
    </html>
  );
}
